CREATE TABLE IF NOT EXISTS Page (
    ID SERIAL PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    CompanyName VARCHAR(100) NULL,
    Email VARCHAR(100) NOT NULL,  
    Phone VARCHAR(25) NOT NULL,
    Info TEXT NOT NULL
)