CREATE TABLE IF NOT EXISTS Site (
    ID SERIAL PRIMARY KEY,
    Domain VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Page (
    ID SERIAL PRIMARY KEY,
    SiteID integer REFERENCES Site,
    Url VARCHAR(100) NOT NULL,
    Title VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS BlockDef (
    ID SERIAL PRIMARY KEY,
    Code VARCHAR(100) NOT NULL,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Block (
    ID SERIAL PRIMARY KEY,
    BlockDefID integer REFERENCES BlockDef,
    PageID integer REFERENCES Page,
    Template VARCHAR(100) NOT NULL
);