DROP TABLE IF EXISTS DatabaseVersion;

DROP TABLE IF EXISTS BlockSetting;
DROP TABLE IF EXISTS BlockSettingDef;
DROP TABLE IF EXISTS Block;
DROP TABLE IF EXISTS BlockDef;
DROP TABLE IF EXISTS BlockContainerArea;
DROP TABLE IF EXISTS BlockContainer;
DROP TABLE IF EXISTS BlockContainerAreaDef;
DROP TABLE IF EXISTS BlockContainerDef;
DROP TABLE IF EXISTS Page;
DROP TABLE IF EXISTS SiteVersion;
DROP TABLE IF EXISTS Site;
DROP TABLE IF EXISTS Admin;
DROP TABLE IF EXISTS Client;