# base ubuntu 14.04
FROM ubuntu:trusty

RUN apt-get update
RUN apt-get install -y nodejs npm

COPY ./docker /home/web/docker

EXPOSE 80
EXPOSE 443

CMD sh /home/web/docker/scripts/web/controlcenterapi.sh