# base ubuntu 16.04
FROM ubuntu:xenial

RUN apt-get update
RUN apt-get -y install postgresql postgresql-contrib

COPY ./docker /home/web/docker

ARG attolloenv=local
ENV attolloenv ${attolloenv}

EXPOSE 5432

CMD sh /home/web/docker/scripts/psql.sh