# base ubuntu 16.04
FROM armv7/armhf-ubuntu:xenial

RUN apt-get update
RUN apt-get install -y curl sudo unzip zip python
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN apt-get install -y nodejs build-essential

COPY ./docker /home/web/docker

ARG attolloenv=local
ENV attolloenv ${attolloenv}

EXPOSE 80
EXPOSE 443

CMD sh /home/web/docker/scripts/web/runnerapi.sh