# base ubuntu 16.04
FROM ubuntu:xenial

RUN apt-get update
RUN apt-get install -y nodejs npm

COPY ./docker /home/web/docker

ARG attolloenv=local
ENV attolloenv ${attolloenv}

CMD sh /home/web/docker/scripts/dev/dev.sh